config/routes.rb
Rails.application.routes.draw do
  get '/game', to: 'games#game'

  get '/score', to: 'games#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def game
    @grid = generate_grid(9)
    @start_time = Time.now
  end

  def score
    @attempt = params[:attempt]
    @grid = params[:grid].split("")
    @start_time = params[:start_time].to_time
    @end_time = Time.now

    @result = run_game(@attempt, @grid, @start_time, @end_time)
  end

  private
  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: end_time - start_time }

    result[:translation] = get_translation(attempt)
    result[:score], result[:message] = score_and_message(
      attempt, result[:translation], grid, result[:time])

    result
  end

  def included?(guess, grid)
    guess.split("").all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    (time_taken > 60.0) ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def score_and_message(attempt, translation, grid, time)
    if included?(attempt.upcase, grid)
      if translation
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def get_translation(word)
    api_key = "cc52afa4-e3f0-493d-8977-f819a8f910f3"
    begin
      response = open("https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key=#{api_key}&input=#{word}")
      json = JSON.parse(response.read.to_s)
      if json['outputs'] && json['outputs'][0] && json['outputs'][0]['output'] && json['outputs'][0]['output'] != word
        return json['outputs'][0]['output']
      end
    rescue
      if File.read('/usr/share/dict/words').upcase.split("\n").include? word.upcase
        return word
      else
        return nil
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/game.html.erb
<h1>The Longest Word Game</h1>
<p>This is the grid <%= @grid.join(" ") %></p>

<form action="<%= score_path %>" method="GET" class="form-inline">
  <div class="form-group">
    <input type="text" name="attempt" class="form-control">
    <input type="hidden" name="grid" value="<%= @grid.join("") %>" class="form-control">
    <input type="hidden" name="start_time" value="<%= @start_time %>" class="form-control">
  </div>
  <button class="btn btn-primary">Submit</button>
</form>

app/views/games/score.html.erb
<h1>Here is the result</h1>

<p class="alert alert-warning">
  Your attempt was : <%= @attempt %>
</p>

<ul class="list unstyle">
  <li>It took you: <%= @result[:time] %></li>
  <li>It means: <%= @result[:translation] %></li>
  <li>You scored: <%= @result[:score] %></li>
  <li><%= @result[:message].capitalize %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>